AWSTemplateFormatVersion: 2010-09-09
Description: The Cf-Stack for the wordpress-db-credentials

Resources:
  DbNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: DATABASE_NAME
      Description: The DatabaseName
      Tier: Standard
      Type: String
      Value: 'wordpressdb'

  DbCredentialSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: wordpressDbCredentials
      Description: The wordpress USER_NAME and PASSWORD
      GenerateSecretString:
        SecretStringTemplate: '{"DATABASE_USER": "root"}'
        GenerateStringKey: "DATABASE_PASSWORD"
        PasswordLength: 12
        ExcludeCharacters: '"@/\'
